/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import classes.AI;
import classes.Admin;
import javax.swing.JLabel;

/**
 *
 * @author Sebastian Rodriguez
 */
public class MainInterfaz extends javax.swing.JFrame {

    /**
     * Creates new form MainInterfaz
     */
    public MainInterfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Colas = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ColasZelda = new javax.swing.JLabel();
        Colas2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ColasSF = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        StreetIMG = new javax.swing.JLabel();
        ZeldaIMG = new javax.swing.JLabel();
        StreetFighterFondo = new javax.swing.JLabel();
        ZeldaFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setText("Street Fighter 6");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 40, 290, 80));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel2.setText("Titulo Principal");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 290, 80));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel3.setText("Zelda: Tears of the Kingdom");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 490, 80));

        Colas.setBackground(new java.awt.Color(0, 0, 102));
        Colas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Colas de prioridad");
        Colas.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        ColasZelda.setBackground(new java.awt.Color(0, 0, 255));
        ColasZelda.setForeground(new java.awt.Color(0, 51, 255));
        jScrollPane1.setViewportView(ColasZelda);

        Colas.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 270, 310));

        jPanel1.add(Colas, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 270, 370));

        Colas2.setBackground(new java.awt.Color(0, 0, 102));
        Colas2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Colas de prioridad");
        Colas2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        ColasSF.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(ColasSF);

        Colas2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 270, 310));

        jPanel1.add(Colas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 210, 270, 370));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Estado de la pelea");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 160, 40));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/VS.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 80, 100));

        StreetIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Ryu.jpg"))); // NOI18N
        jPanel2.add(StreetIMG, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 150, 150));

        ZeldaIMG.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        ZeldaIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Link.jpg"))); // NOI18N
        jPanel2.add(ZeldaIMG, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 150, 150));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, 440, 390));

        StreetFighterFondo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        StreetFighterFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/StreetFighterFondo.jpg"))); // NOI18N
        StreetFighterFondo.setToolTipText("");
        jPanel1.add(StreetFighterFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, 810, 840));

        ZeldaFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/zeldaFondo.jpg"))); // NOI18N
        jPanel1.add(ZeldaFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 840));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, 840));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainInterfaz().setVisible(true);
            }
        });

        // Crear instancias de las clases necesarias
        Admin admin = new Admin();
        AI ai = new AI();

        // Inicializar personajes y colocarlos en las colas
        admin.initializeCharacters();

        // Simular rondas de la IA
        for (int round = 1; round <= 5; round++) { // Ejemplo: 5 rondas
            System.out.println("\n--- Ronda " + round + " ---");

            // Mostrar las colas antes de la ronda
            admin.printQueues();

            // Seleccionar personajes para el combate desde las colas
            classes.Character[] charactersForBattle = admin.selectCharactersForBattle();
            classes.Character zeldaCharacter = charactersForBattle[0];
            classes.Character streetFighterCharacter = charactersForBattle[1];

            if (zeldaCharacter != null && streetFighterCharacter != null) {
                System.out.println("Inicia el combate: " + zeldaCharacter.getName() + " vs " + streetFighterCharacter.getName());
            }

            // Procesar la batalla en la IA
            ai.processBattle(zeldaCharacter, streetFighterCharacter);

            // Mostrar las colas antes de la ronda
            admin.actualizarColasEnInterfaz();

            // Actualizar las colas después de la ronda
//            admin.updateQueues(); ESTO HACE QUE SE SUBAN LAS POSICIONES 1 DE LAS COLAS AL FINAL DE CADA RONDA.
        }

        // Mostrar las colas al final de la simulación
        System.out.println("\n--- Colas finales ---");
        admin.printQueues();
    }

    public static JLabel getStreetIMG() {
        return StreetIMG;
    }

    public static void setStreetIMG(JLabel StreetIMG) {
        MainInterfaz.StreetIMG = StreetIMG;
    }

    public static JLabel getZeldaIMG() {
        return ZeldaIMG;
    }

    public static void setZeldaIMG(JLabel ZeldaIMG) {
        MainInterfaz.ZeldaIMG = ZeldaIMG;
    }

    public static JLabel getColasSF() {
        return ColasSF;
    }

    public static void setColasSF(JLabel ColasSF) {
        MainInterfaz.ColasSF = ColasSF;
    }

    public static JLabel getColasZelda() {
        return ColasZelda;
    }

    public static void setColasZelda(JLabel ColasZelda) {
        MainInterfaz.ColasZelda = ColasZelda;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Colas;
    private javax.swing.JPanel Colas2;
    public static javax.swing.JLabel ColasSF;
    public static javax.swing.JLabel ColasZelda;
    private javax.swing.JLabel StreetFighterFondo;
    public static javax.swing.JLabel StreetIMG;
    private javax.swing.JLabel ZeldaFondo;
    public static javax.swing.JLabel ZeldaIMG;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
